---
title: "About this Study and Repository"
---

### **Safer and Smarter: Leveraging Interpretation-Guided Modeling and Data Merging of Disease and Environmental Data for Plant Disease Risk Prediction**

**Kaique S. Alves^1,2^; Denis A. Shah^3^; Helene. R. Dillard^4^; Emerson M. Del Ponte^1^; Sarah J. Pethybridge^2\*^**

> ^**1**^ Departamento de Fitopatologia, Universidade Federal de Viçosa, Viçosa, MG 36570-900, Brazil
>
> ^**2**^ Plant Pathology & Plant-Microbe Biology Section, School of Integrative Plant Science, Cornell University, Geneva, NY 14456, USA
>
> ^**3**^ Department of Plant Pathology, Kansas State University, Manhattan, KS 66506, USA
>
> ^**4**^ College of Agricultural and Environmental Sciences, University of California, Davis, CA 95616, USA
>
> \***Corresponding author**: Sarah J. Pethybridge
>
> **Email**: sjp277@cornell.edu

## Summary

We developed a workflow for enhancing small observational datasets to model plant disease risk. Using white mold in snap beans as a case study, we fused georeferenced disease observations with soil variables and features from downscaled weather data. Functional data analysis identified key periods in the weather series, and random forests highlighted critical predictors, which were used to build a simpler logistic regression model. This approach demonstrates how machine learning can guide the development of calibrated, practical models, addressing overfitting and aligning analytical complexity with dataset size.



## About this website

This website is intended to help you reproduce our complete data analysis workflow using R. It contains all the scripts and documentation you need to replicate the study and understand each step of the process.

The full research compendium with data and scripts used for this study is stored in an [Open Science Framework](https://osf.io/){target="_blank"} repository and can be accessed [here](https://osf.io/v53py/){target="_blank"}. 



## General instructions

The analyses code were written using `R version 4.4.1` and scripted on [Quarto](https://quarto.org/){target="_blank"} (`.qmd`) documents. Before starting, please ensure you have the necessary software installed:

- **R:**  
  If you haven't installed R yet, download it from the [Comprehensive R Archive Network (CRAN)](https://cran.r-project.org/).

- **RStudio:**  
  For an enhanced development environment, download RStudio from the [RStudio Download Page](https://posit.co/download/rstudio-desktop/).

- **Quarto:**
  Follow instruction on the [Get Started page](https://quarto.org/docs/get-started/){target="_blank"} of the Quarto website to get started with Quarto documents in R.



## Downloading the codes repository

To Download the codes and run the analysis in your machine, please click [here](https://github.com/AlvesKS/paper-white-mold-prediction-modeling/archive/refs/heads/main.zip). This will download a `.zip` file. You should unzip it before runing the codes. 


### Cloning 

To clone the repository, you'll need Git installed on your system. Then, simply open your terminal (or command prompt on Windows) and run the following command:

```{r eval=FALSE}
git clone https://github.com/AlvesKS/paper-white-mold-prediction-modeling.git
```


## Running the codes

After the downloading the repository from the link provided above, refer to the [Getting started](code_get_started_data.html) page to run the codes in your machine.


### Repository Structure

- **Running the Codes:**  
  As noted in the "Running the codes" section, once you download the repository, refer to the [Getting started](getting-started.html) page to execute the R scripts on your machine.

- **Data Sources:**  
  The repository is organized into several key sections:
  - **Getting started:** Initial setup instructions for downloading the data necessary to run the analysis. **You should start here!**
  - **Weather data:** Datasets and scripts related to weather variables.
  - **Soil data:** Code for processing soil data.
  - **Canopy closure:** Predicting canopy closure.
  - **Fuse the white mold datasets:** Procedures to merge and clean the datasets.

- **Functional Data Analysis:**  
  This section is divided into:
  - **Exploratory Analysis:** Preliminary data exploration and visualization.
  - **Function-on-Scalar Regressions for the white mold data:** Advanced functional data analysis to identify significant weather windows.

- **Data Analysis:**  
  Contains the final analysis and modeling:
  - **Models for White Mold:** Detailed machine learning modeling, validation and their interpretation.




### How to Reproduce the Analysis

1. **Download the Repository:**  
   Clone or download the repository from the link provided above.

2. **Install Software:**  
   Make sure that both R and RStudio are installed on your system using the links provided above.

3. **Run the Codes:**  
   Open the `getting-started.qmd` file in RStudio and follow the step-by-step instructions within to run the code sections sequentially.

4. **Explore the Sections:**  
   Navigate through the sections on Data Sources, Functional Data Analysis, and Data Analysis to understand the workflow and explore the results.

By following these steps, you will be able to fully reproduce the data analysis presented in this study. If you encounter any issues, please refer to the documentation within each section or reach out to the repository maintainer for assistance.



## Research compendium

::: {.callout-note appearance="simple"}
## Please cite this research compendium as:

Alves, K. S., Shah, D. A., Dillard, H. R., Del Ponte, E. M., & Pethybridge, S. J. (2022, August 3). Research Compendium: Safer and Smarter: Leveraging Interpretation-Guided Modeling and Data Merging of Disease and Environmental Data for Plant Disease Risk Prediction. <https://doi.org/10.17605/OSF.IO/V53PY>
:::


## Original article

::: {.callout-note appearance="simple"}
# This [repository](https://osf.io/v53py/){target="_blank"} contains the data and code for our article:

Alves, K.S., Shah, D.A., Dillard, H.R., Del Ponte, E.M., Pethybridge, S.J. (YYYY) Safer and Smarter: Leveraging Interpretation-Guided Modeling and Data Merging of Disease and Environmental Data for Plant Disease Risk Prediction. Name of journal/book <https://doi.org/xxx/xxx>
:::

## Read the Preprint

::: {.callout-note appearance="simple"}
# Our pre-print is online on the OSF preprint server:

Alves, K.S., Shah, D.A., Dillard, H.R., Del Ponte, E.M., Pethybridge, S.J. (2024) Safer and Smarter: Leveraging Interpretation-Guided Modeling and Data Merging of Disease and Environmental Data for Plant Disease Risk Prediction. Online at <https://doi.org/10.31219/osf.io/9tgau>
:::

# Meta

## Licensing

**Code**: MIT year: 2022, copyright holder: Kaique S. Alves

## Repository maintainer

**Kaique S. Alves**

-   *Plant Health Scientist within the Global Plant Health team of Breeding - Bayer Crop sciecce*

-   *D.Sc in the [Plant Pathology graduate program](http://www.dfp.ufv.br/graduate/about-the-program/){target="_blank"} from Universidade Federal de Viçosa in Brazil.*

-   *Visiting Scholar in the [EVADE program](https://blogs.cornell.edu/pethybridgelab/){target="_blank"} of the Plant Pathology & Plant-Microbe Biology Section, School of Integrative Plant Science, Cornell University.*

[**Personal website**](https://kaiquealves.netlify.app/){target="_blank"} \| [**GitHub**](https://github.com/AlvesKS){target="_blank"} \| [**Google Scholar**](https://scholar.google.com.br/citations?user=wTzslqsAAAAJ&hl){target="_blank"}
